/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTeamsRouteImport } from './routes/_authenticated/teams'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedLeaguesRouteImport } from './routes/_authenticated/leagues'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMatchesIndexRouteImport } from './routes/_authenticated/matches.index'
import { Route as AuthenticatedMatchesNewRouteImport } from './routes/_authenticated/matches.new'
import { Route as AuthenticatedMatchesIdRouteImport } from './routes/_authenticated/matches.$id'
import { Route as AuthenticatedMatchesIdIndexRouteImport } from './routes/_authenticated/matches.$id.index'
import { Route as AuthenticatedMatchesIdStatsRouteImport } from './routes/_authenticated/matches.$id.stats'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamsRoute = AuthenticatedTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaguesRoute = AuthenticatedLeaguesRouteImport.update({
  id: '/leagues',
  path: '/leagues',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMatchesIndexRoute =
  AuthenticatedMatchesIndexRouteImport.update({
    id: '/matches/',
    path: '/matches/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMatchesNewRoute = AuthenticatedMatchesNewRouteImport.update({
  id: '/matches/new',
  path: '/matches/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMatchesIdRoute = AuthenticatedMatchesIdRouteImport.update({
  id: '/matches/$id',
  path: '/matches/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMatchesIdIndexRoute =
  AuthenticatedMatchesIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMatchesIdRoute,
  } as any)
const AuthenticatedMatchesIdStatsRoute =
  AuthenticatedMatchesIdStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => AuthenticatedMatchesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/leagues': typeof AuthenticatedLeaguesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/teams': typeof AuthenticatedTeamsRoute
  '/matches/$id': typeof AuthenticatedMatchesIdRouteWithChildren
  '/matches/new': typeof AuthenticatedMatchesNewRoute
  '/matches/': typeof AuthenticatedMatchesIndexRoute
  '/matches/$id/stats': typeof AuthenticatedMatchesIdStatsRoute
  '/matches/$id/': typeof AuthenticatedMatchesIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/leagues': typeof AuthenticatedLeaguesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/teams': typeof AuthenticatedTeamsRoute
  '/': typeof AuthenticatedIndexRoute
  '/matches/new': typeof AuthenticatedMatchesNewRoute
  '/matches': typeof AuthenticatedMatchesIndexRoute
  '/matches/$id/stats': typeof AuthenticatedMatchesIdStatsRoute
  '/matches/$id': typeof AuthenticatedMatchesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/leagues': typeof AuthenticatedLeaguesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/teams': typeof AuthenticatedTeamsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/matches/$id': typeof AuthenticatedMatchesIdRouteWithChildren
  '/_authenticated/matches/new': typeof AuthenticatedMatchesNewRoute
  '/_authenticated/matches/': typeof AuthenticatedMatchesIndexRoute
  '/_authenticated/matches/$id/stats': typeof AuthenticatedMatchesIdStatsRoute
  '/_authenticated/matches/$id/': typeof AuthenticatedMatchesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/leagues'
    | '/settings'
    | '/teams'
    | '/matches/$id'
    | '/matches/new'
    | '/matches/'
    | '/matches/$id/stats'
    | '/matches/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/admin'
    | '/leagues'
    | '/settings'
    | '/teams'
    | '/'
    | '/matches/new'
    | '/matches'
    | '/matches/$id/stats'
    | '/matches/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/leagues'
    | '/_authenticated/settings'
    | '/_authenticated/teams'
    | '/_authenticated/'
    | '/_authenticated/matches/$id'
    | '/_authenticated/matches/new'
    | '/_authenticated/matches/'
    | '/_authenticated/matches/$id/stats'
    | '/_authenticated/matches/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teams': {
      id: '/_authenticated/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthenticatedTeamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leagues': {
      id: '/_authenticated/leagues'
      path: '/leagues'
      fullPath: '/leagues'
      preLoaderRoute: typeof AuthenticatedLeaguesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matches/': {
      id: '/_authenticated/matches/'
      path: '/matches'
      fullPath: '/matches/'
      preLoaderRoute: typeof AuthenticatedMatchesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matches/new': {
      id: '/_authenticated/matches/new'
      path: '/matches/new'
      fullPath: '/matches/new'
      preLoaderRoute: typeof AuthenticatedMatchesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matches/$id': {
      id: '/_authenticated/matches/$id'
      path: '/matches/$id'
      fullPath: '/matches/$id'
      preLoaderRoute: typeof AuthenticatedMatchesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matches/$id/': {
      id: '/_authenticated/matches/$id/'
      path: '/'
      fullPath: '/matches/$id/'
      preLoaderRoute: typeof AuthenticatedMatchesIdIndexRouteImport
      parentRoute: typeof AuthenticatedMatchesIdRoute
    }
    '/_authenticated/matches/$id/stats': {
      id: '/_authenticated/matches/$id/stats'
      path: '/stats'
      fullPath: '/matches/$id/stats'
      preLoaderRoute: typeof AuthenticatedMatchesIdStatsRouteImport
      parentRoute: typeof AuthenticatedMatchesIdRoute
    }
  }
}

interface AuthenticatedMatchesIdRouteChildren {
  AuthenticatedMatchesIdStatsRoute: typeof AuthenticatedMatchesIdStatsRoute
  AuthenticatedMatchesIdIndexRoute: typeof AuthenticatedMatchesIdIndexRoute
}

const AuthenticatedMatchesIdRouteChildren: AuthenticatedMatchesIdRouteChildren =
  {
    AuthenticatedMatchesIdStatsRoute: AuthenticatedMatchesIdStatsRoute,
    AuthenticatedMatchesIdIndexRoute: AuthenticatedMatchesIdIndexRoute,
  }

const AuthenticatedMatchesIdRouteWithChildren =
  AuthenticatedMatchesIdRoute._addFileChildren(
    AuthenticatedMatchesIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedLeaguesRoute: typeof AuthenticatedLeaguesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamsRoute: typeof AuthenticatedTeamsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedMatchesIdRoute: typeof AuthenticatedMatchesIdRouteWithChildren
  AuthenticatedMatchesNewRoute: typeof AuthenticatedMatchesNewRoute
  AuthenticatedMatchesIndexRoute: typeof AuthenticatedMatchesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedLeaguesRoute: AuthenticatedLeaguesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamsRoute: AuthenticatedTeamsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedMatchesIdRoute: AuthenticatedMatchesIdRouteWithChildren,
  AuthenticatedMatchesNewRoute: AuthenticatedMatchesNewRoute,
  AuthenticatedMatchesIndexRoute: AuthenticatedMatchesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
